// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.analytics;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** CatalogEntry */
public class CatalogEntry {

  @JsonProperty("kind")
  private String kind;

  @JsonProperty("description")
  private String description;

  @JsonProperty("roots")
  private List<String> roots = new ArrayList<>();

  @JsonProperty("requires")
  private List<String> requires = new ArrayList<>();

  public CatalogEntry setKind(String kind) {
    this.kind = kind;
    return this;
  }

  /** Field identifier. */
  @javax.annotation.Nonnull
  public String getKind() {
    return kind;
  }

  public CatalogEntry setDescription(String description) {
    this.description = description;
    return this;
  }

  /** Human-readable description of the field. */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public CatalogEntry setRoots(List<String> roots) {
    this.roots = roots;
    return this;
  }

  public CatalogEntry addRoots(String rootsItem) {
    this.roots.add(rootsItem);
    return this;
  }

  /**
   * Root stages the field depends on. Two fields are combinable in one query only when their roots
   * intersect.
   */
  @javax.annotation.Nonnull
  public List<String> getRoots() {
    return roots;
  }

  public CatalogEntry setRequires(List<String> requires) {
    this.requires = requires;
    return this;
  }

  public CatalogEntry addRequires(String requiresItem) {
    this.requires.add(requiresItem);
    return this;
  }

  /** Public ACL identifiers required to read the field, for example `clickAnalyticsEnabled`. */
  @javax.annotation.Nonnull
  public List<String> getRequires() {
    return requires;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogEntry catalogEntry = (CatalogEntry) o;
    return (
      Objects.equals(this.kind, catalogEntry.kind) &&
      Objects.equals(this.description, catalogEntry.description) &&
      Objects.equals(this.roots, catalogEntry.roots) &&
      Objects.equals(this.requires, catalogEntry.requires)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, description, roots, requires);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogEntry {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    roots: ").append(toIndentedString(roots)).append("\n");
    sb.append("    requires: ").append(toIndentedString(requires)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
