// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.analytics;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** Currency code. */
public class CurrenciesValue {

  @JsonProperty("currency")
  private String currency;

  @JsonProperty("revenue")
  private Float revenue;

  public CurrenciesValue setCurrency(String currency) {
    this.currency = currency;
    return this;
  }

  /** Currency code. */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public CurrenciesValue setRevenue(Float revenue) {
    this.revenue = revenue;
    return this;
  }

  /** Revenue associated with this search in this currency. */
  @javax.annotation.Nullable
  public Float getRevenue() {
    return revenue;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrenciesValue currenciesValue = (CurrenciesValue) o;
    return Objects.equals(this.currency, currenciesValue.currency) && Objects.equals(this.revenue, currenciesValue.revenue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, revenue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrenciesValue {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
