// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.analytics;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** TopHitsResponseWithRevenueAnalytics */
@JsonDeserialize(as = TopHitsResponseWithRevenueAnalytics.class)
public class TopHitsResponseWithRevenueAnalytics implements GetTopHitsResponse {

  @JsonProperty("hits")
  private List<TopHitWithRevenueAnalytics> hits = new ArrayList<>();

  public TopHitsResponseWithRevenueAnalytics setHits(List<TopHitWithRevenueAnalytics> hits) {
    this.hits = hits;
    return this;
  }

  public TopHitsResponseWithRevenueAnalytics addHits(TopHitWithRevenueAnalytics hitsItem) {
    this.hits.add(hitsItem);
    return this;
  }

  /** Most frequent search results with click, conversion, and revenue metrics. */
  @javax.annotation.Nonnull
  public List<TopHitWithRevenueAnalytics> getHits() {
    return hits;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopHitsResponseWithRevenueAnalytics topHitsResponseWithRevenueAnalytics = (TopHitsResponseWithRevenueAnalytics) o;
    return Objects.equals(this.hits, topHitsResponseWithRevenueAnalytics.hits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopHitsResponseWithRevenueAnalytics {\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
