name: Setup

description: Setup CI environment.

runs:
  using: composite
  steps:
    - name: Restore cache
      uses: ./.github/actions/cache

    - name: Update apt packages
      shell: bash
      run: sudo apt update

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11.0.4

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc

    - name: Install JavaScript Dependencies
      shell: bash
      run: yarn install
