# path
IndexName:
  name: indexName
  in: path
  description: The index in which to perform the request.
  required: true
  schema:
    type: string
    example: myIndexName

ObjectID:
  name: objectID
  in: path
  description: Unique identifier of an object.
  required: true
  schema:
    type: string
    example: '123'

# query
Index:
  in: query
  name: index
  description: The index name to target.
  required: true
  schema:
    type: string

StartDate:
  in: query
  name: startDate
  description: The lower bound timestamp (a date, a string like "2006-01-02") of the period to analyze.
  schema:
    type: string
    example: 1999-09-19
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

EndDate:
  in: query
  name: endDate
  description: The upper bound timestamp (a date, a string like "2006-01-02") of the period to analyze.
  schema:
    type: string
    example: 2000-01-21
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

ForwardToReplicas:
  in: query
  name: forwardToReplicas
  description: When true, changes are also propagated to replicas of the given indexName.
  schema:
    type: boolean

Page:
  in: query
  name: page
  description: Requested page (zero-based). When specified, will retrieve a specific page; the page size is implicitly set to 100. When null, will retrieve all indices (no pagination).
  schema:
    type: integer
    nullable: true
    default: null

PageDefault0:
  in: query
  name: page
  description: Requested page (zero-based). When specified, will retrieve a specific page; the page size is implicitly set to 100. When null, will retrieve all indices (no pagination).
  schema:
    type: integer
    nullable: true
    default: 0

HitsPerPage:
  in: query
  name: hitsPerPage
  description: Maximum number of objects to retrieve.
  schema:
    type: integer
    default: 100

# misc
taskID:
  type: integer
  description: taskID of the indexing task to wait for.

objectID:
  type: string
  description: Unique identifier of the object.

id:
  type: string
  description: objectID of the inserted object.

objectIDs:
  type: array
  items:
    type: string
  description: List of objectID.

queryID:
  type: string
  pattern: '^[a-f0-9]{32}$'
  example: 43b15df305339e827f0ac0bdc5ebcaa7

abTestID:
  type: integer
  description: If a search encounters an index that is being A/B tested, abTestID reports the ongoing A/B test ID.

abTestVariantID:
  type: integer
  description: If a search encounters an index that is being A/B tested, abTestVariantID reports the variant ID of the index used.

createdAt:
  type: string
  format: date-time
  description: Date of creation (ISO-8601 format).

updatedAt:
  type: string
  format: date-time
  description: Date of last update (ISO-8601 format).

deletedAt:
  type: string
  format: date-time
  description: Date of deletion (ISO-8601 format).

indexName:
  type: string
  example: products
  description: The Algolia index name.

hitsPerPage:
  type: integer
  default: 20
  description: Maximum number of hits in a page. Minimum is 1, maximum is 1000.

query:
  type: string
  description: Full text query.
  default: ''

page:
  type: integer
  default: 0
  description: Requested page (zero-based).
