// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

/** Type of the Authentication, defines what kind of object is stored in the input. */
public enum AuthenticationType {
  GOOGLE_SERVICE_ACCOUNT("googleServiceAccount"),

  BASIC("basic"),

  API_KEY("apiKey"),

  OAUTH("oauth"),

  ALGOLIA("algolia");

  private final String value;

  AuthenticationType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AuthenticationType fromValue(String value) {
    for (AuthenticationType b : AuthenticationType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
