// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** API response for a successful update of an authentication resource. */
public class AuthenticationUpdateResponse {

  @JsonProperty("authenticationID")
  private String authenticationID;

  @JsonProperty("name")
  private String name;

  @JsonProperty("updatedAt")
  private String updatedAt;

  public AuthenticationUpdateResponse setAuthenticationID(String authenticationID) {
    this.authenticationID = authenticationID;
    return this;
  }

  /** Universally unique identifier (UUID) of an authentication resource. */
  @javax.annotation.Nonnull
  public String getAuthenticationID() {
    return authenticationID;
  }

  public AuthenticationUpdateResponse setName(String name) {
    this.name = name;
    return this;
  }

  /** Descriptive name for the resource. */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public AuthenticationUpdateResponse setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /** Date and time when the resource was last updated, in RFC 3339 format. */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationUpdateResponse authenticationUpdateResponse = (AuthenticationUpdateResponse) o;
    return (
      Objects.equals(this.authenticationID, authenticationUpdateResponse.authenticationID) &&
      Objects.equals(this.name, authenticationUpdateResponse.name) &&
      Objects.equals(this.updatedAt, authenticationUpdateResponse.updatedAt)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationID, name, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationUpdateResponse {\n");
    sb.append("    authenticationID: ").append(toIndentedString(authenticationID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
