// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.algolia.exceptions.AlgoliaRuntimeException;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Logger;

/** AuthInput */
@JsonDeserialize(using = AuthInput.Deserializer.class)
public interface AuthInput {
  // AuthInput as Map<String, String> wrapper.
  static AuthInput of(Map<String, String> value) {
    return new MapOfStringStringWrapper(value);
  }

  // AuthInput as Map<String, String> wrapper.
  @JsonSerialize(using = MapOfStringStringWrapper.Serializer.class)
  class MapOfStringStringWrapper implements AuthInput {

    private final Map<String, String> value;

    MapOfStringStringWrapper(Map<String, String> value) {
      this.value = value;
    }

    public Map<String, String> getValue() {
      return value;
    }

    static class Serializer extends JsonSerializer<MapOfStringStringWrapper> {

      @Override
      public void serialize(MapOfStringStringWrapper value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        gen.writeObject(value.getValue());
      }
    }
  }

  class Deserializer extends JsonDeserializer<AuthInput> {

    private static final Logger LOGGER = Logger.getLogger(Deserializer.class.getName());

    @Override
    public AuthInput deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
      JsonNode tree = jp.readValueAsTree();
      // deserialize AuthOAuth
      if (tree.isObject() && tree.has("url") && tree.has("client_id") && tree.has("client_secret") && tree.has("code")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthOAuth.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf AuthOAuth (error: " + e.getMessage() + ") (type: AuthOAuth)");
        }
      }
      // deserialize AuthGoogleServiceAccount
      if (tree.isObject() && tree.has("clientEmail") && tree.has("privateKey")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthGoogleServiceAccount.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AuthGoogleServiceAccount (error: " + e.getMessage() + ") (type: AuthGoogleServiceAccount)"
          );
        }
      }
      // deserialize AuthBasic
      if (tree.isObject() && tree.has("username") && tree.has("password")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthBasic.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf AuthBasic (error: " + e.getMessage() + ") (type: AuthBasic)");
        }
      }
      // deserialize AuthAPIKey
      if (tree.isObject() && tree.has("key")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthAPIKey.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf AuthAPIKey (error: " + e.getMessage() + ") (type: AuthAPIKey)");
        }
      }
      // deserialize AuthAlgolia
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthAlgolia.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf AuthAlgolia (error: " + e.getMessage() + ") (type: AuthAlgolia)");
        }
      }
      // deserialize AuthAlgoliaInsights
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AuthAlgoliaInsights.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf AuthAlgoliaInsights (error: " + e.getMessage() + ") (type: AuthAlgoliaInsights)");
        }
      }
      // deserialize Map<String, String>
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          Map<String, String> value = parser.readValueAs(new TypeReference<Map<String, String>>() {});
          return new AuthInput.MapOfStringStringWrapper(value);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf Map<String, String> (error: " + e.getMessage() + ") (type: Map<String, String>)");
        }
      }
      throw new AlgoliaRuntimeException(String.format("Failed to deserialize json element: %s", tree));
    }

    /** Handle deserialization of the 'null' value. */
    @Override
    public AuthInput getNullValue(DeserializationContext ctxt) throws JsonMappingException {
      throw new JsonMappingException(ctxt.getParser(), "AuthInput cannot be null");
    }
  }
}
