// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** API request body for updating a destination. */
public class DestinationUpdate {

  @JsonProperty("type")
  private DestinationType type;

  @JsonProperty("name")
  private String name;

  @JsonProperty("input")
  private DestinationInput input;

  @JsonProperty("authenticationID")
  private String authenticationID;

  @JsonProperty("transformationIDs")
  private List<String> transformationIDs;

  public DestinationUpdate setType(DestinationType type) {
    this.type = type;
    return this;
  }

  /** Get type */
  @javax.annotation.Nullable
  public DestinationType getType() {
    return type;
  }

  public DestinationUpdate setName(String name) {
    this.name = name;
    return this;
  }

  /** Descriptive name for the resource. */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public DestinationUpdate setInput(DestinationInput input) {
    this.input = input;
    return this;
  }

  /** Get input */
  @javax.annotation.Nullable
  public DestinationInput getInput() {
    return input;
  }

  public DestinationUpdate setAuthenticationID(String authenticationID) {
    this.authenticationID = authenticationID;
    return this;
  }

  /** Universally unique identifier (UUID) of an authentication resource. */
  @javax.annotation.Nullable
  public String getAuthenticationID() {
    return authenticationID;
  }

  public DestinationUpdate setTransformationIDs(List<String> transformationIDs) {
    this.transformationIDs = transformationIDs;
    return this;
  }

  public DestinationUpdate addTransformationIDs(String transformationIDsItem) {
    if (this.transformationIDs == null) {
      this.transformationIDs = new ArrayList<>();
    }
    this.transformationIDs.add(transformationIDsItem);
    return this;
  }

  /** Get transformationIDs */
  @javax.annotation.Nullable
  public List<String> getTransformationIDs() {
    return transformationIDs;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinationUpdate destinationUpdate = (DestinationUpdate) o;
    return (
      Objects.equals(this.type, destinationUpdate.type) &&
      Objects.equals(this.name, destinationUpdate.name) &&
      Objects.equals(this.input, destinationUpdate.input) &&
      Objects.equals(this.authenticationID, destinationUpdate.authenticationID) &&
      Objects.equals(this.transformationIDs, destinationUpdate.transformationIDs)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, input, authenticationID, transformationIDs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinationUpdate {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    authenticationID: ").append(toIndentedString(authenticationID)).append("\n");
    sb.append("    transformationIDs: ").append(toIndentedString(transformationIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
