// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** RunListResponse */
public class RunListResponse {

  @JsonProperty("runs")
  private List<Run> runs = new ArrayList<>();

  @JsonProperty("pagination")
  private Pagination pagination;

  @JsonProperty("window")
  private Window window;

  public RunListResponse setRuns(List<Run> runs) {
    this.runs = runs;
    return this;
  }

  public RunListResponse addRuns(Run runsItem) {
    this.runs.add(runsItem);
    return this;
  }

  /** Get runs */
  @javax.annotation.Nonnull
  public List<Run> getRuns() {
    return runs;
  }

  public RunListResponse setPagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /** Get pagination */
  @javax.annotation.Nonnull
  public Pagination getPagination() {
    return pagination;
  }

  public RunListResponse setWindow(Window window) {
    this.window = window;
    return this;
  }

  /** Get window */
  @javax.annotation.Nonnull
  public Window getWindow() {
    return window;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunListResponse runListResponse = (RunListResponse) o;
    return (
      Objects.equals(this.runs, runListResponse.runs) &&
      Objects.equals(this.pagination, runListResponse.pagination) &&
      Objects.equals(this.window, runListResponse.window)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(runs, pagination, window);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunListResponse {\n");
    sb.append("    runs: ").append(toIndentedString(runs)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    window: ").append(toIndentedString(window)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
