// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/** RunTaskPayload */
public class RunTaskPayload {

  @JsonProperty("runMetadata")
  private Map<String, Object> runMetadata;

  public RunTaskPayload setRunMetadata(Map<String, Object> runMetadata) {
    this.runMetadata = runMetadata;
    return this;
  }

  public RunTaskPayload putRunMetadata(String key, Object runMetadataItem) {
    if (this.runMetadata == null) {
      this.runMetadata = new HashMap<>();
    }
    this.runMetadata.put(key, runMetadataItem);
    return this;
  }

  /** Additional information that will be passed to the created run. */
  @javax.annotation.Nullable
  public Map<String, Object> getRunMetadata() {
    return runMetadata;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunTaskPayload runTaskPayload = (RunTaskPayload) o;
    return Objects.equals(this.runMetadata, runTaskPayload.runMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(runMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunTaskPayload {\n");
    sb.append("    runMetadata: ").append(toIndentedString(runMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
