// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** List of available AI models for transformation purposes. */
public class TransformationModels {

  @JsonProperty("llms")
  private List<Model> llms = new ArrayList<>();

  public TransformationModels setLlms(List<Model> llms) {
    this.llms = llms;
    return this;
  }

  public TransformationModels addLlms(Model llmsItem) {
    this.llms.add(llmsItem);
    return this;
  }

  /** Get llms */
  @javax.annotation.Nonnull
  public List<Model> getLlms() {
    return llms;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransformationModels transformationModels = (TransformationModels) o;
    return Objects.equals(this.llms, transformationModels.llms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(llms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransformationModels {\n");
    sb.append("    llms: ").append(toIndentedString(llms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
