// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.search;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/** A/B test variant for an index. */
public class FetchedIndexAbTestVariant {

  @JsonProperty("indexName")
  private String indexName;

  @JsonProperty("percentage")
  private Integer percentage;

  @JsonProperty("customSearchParameters")
  private String customSearchParameters;

  @JsonProperty("payload")
  private Map<String, Object> payload;

  public FetchedIndexAbTestVariant setIndexName(String indexName) {
    this.indexName = indexName;
    return this;
  }

  /** Index name of the variant. Only present for v0/v1 tests; in v2 this moves into `payload`. */
  @javax.annotation.Nullable
  public String getIndexName() {
    return indexName;
  }

  public FetchedIndexAbTestVariant setPercentage(Integer percentage) {
    this.percentage = percentage;
    return this;
  }

  /** Percentage of search traffic routed to this variant. */
  @javax.annotation.Nonnull
  public Integer getPercentage() {
    return percentage;
  }

  public FetchedIndexAbTestVariant setCustomSearchParameters(String customSearchParameters) {
    this.customSearchParameters = customSearchParameters;
    return this;
  }

  /**
   * URL-encoded custom search parameters applied to this variant. Only present for v0/v1 tests; in
   * v2 this moves into `payload`.
   */
  @javax.annotation.Nullable
  public String getCustomSearchParameters() {
    return customSearchParameters;
  }

  public FetchedIndexAbTestVariant setPayload(Map<String, Object> payload) {
    this.payload = payload;
    return this;
  }

  public FetchedIndexAbTestVariant putPayload(String key, Object payloadItem) {
    if (this.payload == null) {
      this.payload = new HashMap<>();
    }
    this.payload.put(key, payloadItem);
    return this;
  }

  /**
   * Type-specific configuration. Only present for v2 and later tests. Shape depends on the parent
   * A/B test's `type`.
   */
  @javax.annotation.Nullable
  public Map<String, Object> getPayload() {
    return payload;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FetchedIndexAbTestVariant fetchedIndexAbTestVariant = (FetchedIndexAbTestVariant) o;
    return (
      Objects.equals(this.indexName, fetchedIndexAbTestVariant.indexName) &&
      Objects.equals(this.percentage, fetchedIndexAbTestVariant.percentage) &&
      Objects.equals(this.customSearchParameters, fetchedIndexAbTestVariant.customSearchParameters) &&
      Objects.equals(this.payload, fetchedIndexAbTestVariant.payload)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(indexName, percentage, customSearchParameters, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FetchedIndexAbTestVariant {\n");
    sb.append("    indexName: ").append(toIndentedString(indexName)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    customSearchParameters: ").append(toIndentedString(customSearchParameters)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
