// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.search;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** HierarchyPathEntry */
public class HierarchyPathEntry {

  @JsonProperty("facetName")
  private String facetName;

  @JsonProperty("facetValue")
  private String facetValue;

  @JsonProperty("depth")
  private Integer depth;

  public HierarchyPathEntry setFacetName(String facetName) {
    this.facetName = facetName;
    return this;
  }

  /** Facet attribute name at this hierarchy level, for example, `categories.lvl0`. */
  @javax.annotation.Nullable
  public String getFacetName() {
    return facetName;
  }

  public HierarchyPathEntry setFacetValue(String facetValue) {
    this.facetValue = facetValue;
    return this;
  }

  /** Facet value at this level of the category hierarchy. */
  @javax.annotation.Nullable
  public String getFacetValue() {
    return facetValue;
  }

  public HierarchyPathEntry setDepth(Integer depth) {
    this.depth = depth;
    return this;
  }

  /** Depth level in the category hierarchy, starting at 0. */
  @javax.annotation.Nullable
  public Integer getDepth() {
    return depth;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HierarchyPathEntry hierarchyPathEntry = (HierarchyPathEntry) o;
    return (
      Objects.equals(this.facetName, hierarchyPathEntry.facetName) &&
      Objects.equals(this.facetValue, hierarchyPathEntry.facetValue) &&
      Objects.equals(this.depth, hierarchyPathEntry.depth)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(facetName, facetValue, depth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HierarchyPathEntry {\n");
    sb.append("    facetName: ").append(toIndentedString(facetName)).append("\n");
    sb.append("    facetValue: ").append(toIndentedString(facetValue)).append("\n");
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
