// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.search;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** WithPrimary */
public class WithPrimary {

  @JsonProperty("primary")
  private String primary;

  public WithPrimary setPrimary(String primary) {
    this.primary = primary;
    return this;
  }

  /** Replica indices only: the name of the primary index for this replica. */
  @javax.annotation.Nullable
  public String getPrimary() {
    return primary;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WithPrimary withPrimary = (WithPrimary) o;
    return Objects.equals(this.primary, withPrimary.primary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WithPrimary {\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
