version: 2.1

commands:
  credentials:
    description: "Fetch temporary credentials if needed"
    steps:
      - run:
          name: Retrieve temporary Algolia credentials if needed
          command: |
            if [ -z "ALGOLIA_APPLICATION_ID_MCM" ]; then
              curl -s https://algoliasearch-client-keygen.herokuapp.com | sh >> $BASH_ENV
            fi

jobs:
  format:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache-8
      - run:
          name: "Check formatting"
          command: mvn com.coveo:fmt-maven-plugin:check

  test-java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache-8
      - credentials
      - run:
          name: "Compile project"
          command: mvn clean compile -pl algoliasearch-apache,algoliasearch-core
      - run:
          name: "Run the tests"
          command: mvn clean test    -pl algoliasearch-apache,algoliasearch-core
      - save_cache:
          key: mvn-cache-8
          paths:
            - "~/.m2"

  test-java-11:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache-11
      - credentials
      - run:
          name: "Compile project"
          command: mvn clean compile
      - run:
          name: "Run the tests"
          command: mvn clean test
      - save_cache:
          key: mvn-cache-11
          paths:
            - "~/.m2"

  release:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache-11
      - run:
          name: Release new version
          command: |
            echo -e "$GPG_KEY" | gpg --import
            if [[ -z "$OSSRH_USERNAME" ]]; then echo '$OSSRH_USERNAME is not set';    exit 1; fi
            if [[ -z "$OSSRH_PASSWORD" ]]; then echo '$OSSRH_PASSWORD is not set';    exit 1; fi
            if [[ -z "$GPG_KEY ]];         then echo '$GPG_KEY' is not set;           exit 1; fi
            if [[ -z "$GPG_KEYNAME ]];     then echo '$GPG_KEYNAME' is not set;       exit 1; fi
            if [[ -z "$GPG_PASSPHRASE ]];  then echo '$GPG_PASSPHRASE' is not set;    exit 1; fi
            echo -e "$GPG_KEY" | gpg --import --no-tty --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback
            mvn -s .circleci/settings.xml clean deploy -P release -DskipTests
      - save_cache:
          key: mvn-cache-11
          paths:
            - "~/.m2"

workflows:
  version: 2
  build:
    codestyle:
      jobs:
        - format:
            filters:
              tags:
                only: /.*/
    test-java-8:
      jobs:
        - test-java-8:
            filters:
              tags:
                only: /.*/
      - test-java-11:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - format
            - test-java-8
            - test-java-11
          filters:
            tags:
              only: /^[1-9]+.[0-9]+.[0-9]+.*/
            branches:
              ignore: /.*/
