// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.querysuggestions;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** AppID */
public class AppID {

  @JsonProperty("appID")
  private String appID;

  public AppID setAppID(String appID) {
    this.appID = appID;
    return this;
  }

  /** Algolia application ID to which this Query Suggestions configuration belongs. */
  @javax.annotation.Nullable
  public String getAppID() {
    return appID;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppID appID = (AppID) o;
    return Objects.equals(this.appID, appID.appID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppID {\n");
    sb.append("    appID: ").append(toIndentedString(appID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
