// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.personalization;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** EventsScoring */
public class EventsScoring {

  @JsonProperty("score")
  private Integer score;

  @JsonProperty("eventName")
  private String eventName;

  @JsonProperty("eventType")
  private EventType eventType;

  public EventsScoring setScore(Integer score) {
    this.score = score;
    return this;
  }

  /** Event score. */
  @javax.annotation.Nonnull
  public Integer getScore() {
    return score;
  }

  public EventsScoring setEventName(String eventName) {
    this.eventName = eventName;
    return this;
  }

  /** Event name. */
  @javax.annotation.Nonnull
  public String getEventName() {
    return eventName;
  }

  public EventsScoring setEventType(EventType eventType) {
    this.eventType = eventType;
    return this;
  }

  /** Get eventType */
  @javax.annotation.Nonnull
  public EventType getEventType() {
    return eventType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsScoring eventsScoring = (EventsScoring) o;
    return (
      Objects.equals(this.score, eventsScoring.score) &&
      Objects.equals(this.eventName, eventsScoring.eventName) &&
      Objects.equals(this.eventType, eventsScoring.eventType)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, eventName, eventType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsScoring {\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
