// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.personalization;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** FacetsScoring */
public class FacetsScoring {

  @JsonProperty("score")
  private Integer score;

  @JsonProperty("facetName")
  private String facetName;

  public FacetsScoring setScore(Integer score) {
    this.score = score;
    return this;
  }

  /** Event score. */
  @javax.annotation.Nonnull
  public Integer getScore() {
    return score;
  }

  public FacetsScoring setFacetName(String facetName) {
    this.facetName = facetName;
    return this;
  }

  /** Facet attribute name. */
  @javax.annotation.Nonnull
  public String getFacetName() {
    return facetName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacetsScoring facetsScoring = (FacetsScoring) o;
    return Objects.equals(this.score, facetsScoring.score) && Objects.equals(this.facetName, facetsScoring.facetName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, facetName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacetsScoring {\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    facetName: ").append(toIndentedString(facetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
