// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.api;

import com.algolia.ApiClient;
import com.algolia.config.*;
import com.algolia.config.ClientOptions;
import com.algolia.exceptions.*;
import com.algolia.model.querysuggestions.*;
import com.algolia.utils.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.time.Duration;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import okhttp3.Response;

public class QuerySuggestionsClient extends ApiClient {

  private static final String[] allowedRegions = { "eu", "us" };

  public QuerySuggestionsClient(String appId, String apiKey, String region) {
    this(appId, apiKey, region, null);
  }

  public QuerySuggestionsClient(String appId, String apiKey, String region, ClientOptions options) {
    super(
      appId,
      apiKey,
      "QuerySuggestions",
      options,
      getDefaultHosts(region),
      Duration.ofMillis(2000L),
      Duration.ofMillis(5000L),
      Duration.ofMillis(30000L)
    );
  }

  private static List<Host> getDefaultHosts(String region) throws AlgoliaRuntimeException {
    List<Host> hosts = new ArrayList<>();

    boolean found = false;
    if (region != null) {
      for (String allowed : allowedRegions) {
        if (allowed.equals(region)) {
          found = true;
          break;
        }
      }
    }

    if (region == null || !found) {
      throw new AlgoliaRuntimeException("`region` is required and must be one of the following: eu, us");
    }

    String url = "query-suggestions.{region}.algolia.com".replace("{region}", region);

    hosts.add(new Host(url, EnumSet.of(CallType.READ, CallType.WRITE)));
    return hosts;
  }

  /**
   * Creates a new Query Suggestions configuration. You can have up to 100 configurations per
   * Algolia application.
   *
   * @param configurationWithIndex (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse createConfig(@Nonnull ConfigurationWithIndex configurationWithIndex, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(createConfigAsync(configurationWithIndex, requestOptions));
  }

  /**
   * Creates a new Query Suggestions configuration. You can have up to 100 configurations per
   * Algolia application.
   *
   * @param configurationWithIndex (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response createConfigWithHTTPInfo(@Nonnull ConfigurationWithIndex configurationWithIndex, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(createConfigWithHTTPInfoAsync(configurationWithIndex, requestOptions));
  }

  /**
   * Creates a new Query Suggestions configuration. You can have up to 100 configurations per
   * Algolia application.
   *
   * @param configurationWithIndex (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse createConfig(@Nonnull ConfigurationWithIndex configurationWithIndex) throws AlgoliaRuntimeException {
    return this.createConfig(configurationWithIndex, null);
  }

  /**
   * Creates a new Query Suggestions configuration. You can have up to 100 configurations per
   * Algolia application.
   *
   * @param configurationWithIndex (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response createConfigWithHTTPInfo(@Nonnull ConfigurationWithIndex configurationWithIndex) throws AlgoliaRuntimeException {
    return this.createConfigWithHTTPInfo(configurationWithIndex, null);
  }

  /**
   * (asynchronously) Creates a new Query Suggestions configuration. You can have up to 100
   * configurations per Algolia application.
   *
   * @param configurationWithIndex (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> createConfigAsync(
    @Nonnull ConfigurationWithIndex configurationWithIndex,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(configurationWithIndex, "Parameter `configurationWithIndex` is required when calling `createConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs").setMethod("POST").setBody(configurationWithIndex).build();
    return executeAsync(request, requestOptions, new TypeReference<BaseResponse>() {});
  }

  /**
   * (asynchronously) Creates a new Query Suggestions configuration. You can have up to 100
   * configurations per Algolia application.
   *
   * @param configurationWithIndex (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> createConfigWithHTTPInfoAsync(
    @Nonnull ConfigurationWithIndex configurationWithIndex,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(configurationWithIndex, "Parameter `configurationWithIndex` is required when calling `createConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs").setMethod("POST").setBody(configurationWithIndex).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Creates a new Query Suggestions configuration. You can have up to 100
   * configurations per Algolia application.
   *
   * @param configurationWithIndex (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> createConfigAsync(@Nonnull ConfigurationWithIndex configurationWithIndex)
    throws AlgoliaRuntimeException {
    return this.createConfigAsync(configurationWithIndex, null);
  }

  /**
   * (asynchronously) Creates a new Query Suggestions configuration. You can have up to 100
   * configurations per Algolia application.
   *
   * @param configurationWithIndex (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> createConfigWithHTTPInfoAsync(@Nonnull ConfigurationWithIndex configurationWithIndex)
    throws AlgoliaRuntimeException {
    return this.createConfigWithHTTPInfoAsync(configurationWithIndex, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customDeleteAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customDeleteWithHTTPInfoAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customDelete(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfo(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customDelete(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfo(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customDelete(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfo(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customDelete`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("DELETE").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customDelete`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("DELETE").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customDeleteAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters)
    throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customDeleteAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customDeleteAsync(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customGetAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customGetWithHTTPInfoAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customGet(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfo(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customGet(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfo(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customGet(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfo(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customGet`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("GET").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customGet`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("GET").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path, Map<String, Object> parameters) throws AlgoliaRuntimeException {
    return this.customGetAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters)
    throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customGetAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customGetAsync(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, Map<String, Object> parameters, Object body, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customPostAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customPostWithHTTPInfoAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, Map<String, Object> parameters, Object body) throws AlgoliaRuntimeException {
    return this.customPost(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, Object body) throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfo(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customPost(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfo(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPost(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfo(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPost`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("POST")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPost`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("POST")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws AlgoliaRuntimeException {
    return this.customPostAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customPostAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPostAsync(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, Map<String, Object> parameters, Object body, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customPutAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(customPutWithHTTPInfoAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, Map<String, Object> parameters, Object body) throws AlgoliaRuntimeException {
    return this.customPut(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, Object body) throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfo(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customPut(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfo(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPut(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfo(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPut`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("PUT")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPut`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("PUT")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws AlgoliaRuntimeException {
    return this.customPutAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customPutAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPutAsync(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path) throws AlgoliaRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, null, null, null);
  }

  /**
   * Deletes a Query Suggestions configuration. Deleting only removes the configuration and stops
   * updates to the Query Suggestions index. To delete the Query Suggestions index itself, use the
   * Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse deleteConfig(@Nonnull String indexName, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(deleteConfigAsync(indexName, requestOptions));
  }

  /**
   * Deletes a Query Suggestions configuration. Deleting only removes the configuration and stops
   * updates to the Query Suggestions index. To delete the Query Suggestions index itself, use the
   * Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response deleteConfigWithHTTPInfo(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(deleteConfigWithHTTPInfoAsync(indexName, requestOptions));
  }

  /**
   * Deletes a Query Suggestions configuration. Deleting only removes the configuration and stops
   * updates to the Query Suggestions index. To delete the Query Suggestions index itself, use the
   * Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse deleteConfig(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.deleteConfig(indexName, null);
  }

  /**
   * Deletes a Query Suggestions configuration. Deleting only removes the configuration and stops
   * updates to the Query Suggestions index. To delete the Query Suggestions index itself, use the
   * Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response deleteConfigWithHTTPInfo(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.deleteConfigWithHTTPInfo(indexName, null);
  }

  /**
   * (asynchronously) Deletes a Query Suggestions configuration. Deleting only removes the
   * configuration and stops updates to the Query Suggestions index. To delete the Query Suggestions
   * index itself, use the Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> deleteConfigAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `deleteConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}", indexName).setMethod("DELETE").build();
    return executeAsync(request, requestOptions, new TypeReference<BaseResponse>() {});
  }

  /**
   * (asynchronously) Deletes a Query Suggestions configuration. Deleting only removes the
   * configuration and stops updates to the Query Suggestions index. To delete the Query Suggestions
   * index itself, use the Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> deleteConfigWithHTTPInfoAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `deleteConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}", indexName).setMethod("DELETE").build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Deletes a Query Suggestions configuration. Deleting only removes the
   * configuration and stops updates to the Query Suggestions index. To delete the Query Suggestions
   * index itself, use the Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> deleteConfigAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.deleteConfigAsync(indexName, null);
  }

  /**
   * (asynchronously) Deletes a Query Suggestions configuration. Deleting only removes the
   * configuration and stops updates to the Query Suggestions index. To delete the Query Suggestions
   * index itself, use the Search API and the `Delete an index` operation.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> deleteConfigWithHTTPInfoAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.deleteConfigWithHTTPInfoAsync(indexName, null);
  }

  /**
   * Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public List<ConfigurationResponse> getAllConfigs(@Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getAllConfigsAsync(requestOptions));
  }

  /**
   * Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getAllConfigsWithHTTPInfo(@Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getAllConfigsWithHTTPInfoAsync(requestOptions));
  }

  /**
   * Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public List<ConfigurationResponse> getAllConfigs() throws AlgoliaRuntimeException {
    return this.getAllConfigs(null);
  }

  /**
   * Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getAllConfigsWithHTTPInfo() throws AlgoliaRuntimeException {
    return this.getAllConfigsWithHTTPInfo(null);
  }

  /**
   * (asynchronously) Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<List<ConfigurationResponse>> getAllConfigsAsync(@Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    HttpRequest request = HttpRequest.builder().setPath("/1/configs").setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<List<ConfigurationResponse>>() {});
  }

  /**
   * (asynchronously) Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getAllConfigsWithHTTPInfoAsync(@Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    HttpRequest request = HttpRequest.builder().setPath("/1/configs").setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<List<ConfigurationResponse>> getAllConfigsAsync() throws AlgoliaRuntimeException {
    return this.getAllConfigsAsync(null);
  }

  /**
   * (asynchronously) Retrieves all Query Suggestions configurations of your Algolia application.
   *
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getAllConfigsWithHTTPInfoAsync() throws AlgoliaRuntimeException {
    return this.getAllConfigsWithHTTPInfoAsync(null);
  }

  /**
   * Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public ConfigurationResponse getConfig(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getConfigAsync(indexName, requestOptions));
  }

  /**
   * Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getConfigWithHTTPInfo(@Nonnull String indexName, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getConfigWithHTTPInfoAsync(indexName, requestOptions));
  }

  /**
   * Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public ConfigurationResponse getConfig(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfig(indexName, null);
  }

  /**
   * Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getConfigWithHTTPInfo(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigWithHTTPInfo(indexName, null);
  }

  /**
   * (asynchronously) Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<ConfigurationResponse> getConfigAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}", indexName).setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<ConfigurationResponse>() {});
  }

  /**
   * (asynchronously) Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getConfigWithHTTPInfoAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getConfig`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}", indexName).setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<ConfigurationResponse> getConfigAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigAsync(indexName, null);
  }

  /**
   * (asynchronously) Retrieves a single Query Suggestions configuration by its index name.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getConfigWithHTTPInfoAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigWithHTTPInfoAsync(indexName, null);
  }

  /**
   * Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public ConfigStatus getConfigStatus(@Nonnull String indexName, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getConfigStatusAsync(indexName, requestOptions));
  }

  /**
   * Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getConfigStatusWithHTTPInfo(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getConfigStatusWithHTTPInfoAsync(indexName, requestOptions));
  }

  /**
   * Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public ConfigStatus getConfigStatus(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigStatus(indexName, null);
  }

  /**
   * Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getConfigStatusWithHTTPInfo(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigStatusWithHTTPInfo(indexName, null);
  }

  /**
   * (asynchronously) Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<ConfigStatus> getConfigStatusAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getConfigStatus`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}/status", indexName).setMethod("GET").build();
    return executeAsync(request, requestOptions, new TypeReference<ConfigStatus>() {});
  }

  /**
   * (asynchronously) Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getConfigStatusWithHTTPInfoAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getConfigStatus`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/configs/{indexName}/status", indexName).setMethod("GET").build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<ConfigStatus> getConfigStatusAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigStatusAsync(indexName, null);
  }

  /**
   * (asynchronously) Reports the status of a Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getConfigStatusWithHTTPInfoAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getConfigStatusWithHTTPInfoAsync(indexName, null);
  }

  /**
   * Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public LogFile getLogFile(@Nonnull String indexName, @Nullable RequestOptions requestOptions) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getLogFileAsync(indexName, requestOptions));
  }

  /**
   * Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getLogFileWithHTTPInfo(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(getLogFileWithHTTPInfoAsync(indexName, requestOptions));
  }

  /**
   * Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public LogFile getLogFile(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getLogFile(indexName, null);
  }

  /**
   * Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response getLogFileWithHTTPInfo(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getLogFileWithHTTPInfo(indexName, null);
  }

  /**
   * (asynchronously) Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<LogFile> getLogFileAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getLogFile`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/logs/{indexName}", indexName).setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<LogFile>() {});
  }

  /**
   * (asynchronously) Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getLogFileWithHTTPInfoAsync(@Nonnull String indexName, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `getLogFile`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/logs/{indexName}", indexName).setMethod("GET").build();

    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<LogFile> getLogFileAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getLogFileAsync(indexName, null);
  }

  /**
   * (asynchronously) Retrieves the logs for a single Query Suggestions index.
   *
   * @param indexName Query Suggestions index name. (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> getLogFileWithHTTPInfoAsync(@Nonnull String indexName) throws AlgoliaRuntimeException {
    return this.getLogFileWithHTTPInfoAsync(indexName, null);
  }

  /**
   * Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse updateConfig(@Nonnull String indexName, @Nonnull Configuration configuration, @Nullable RequestOptions requestOptions)
    throws AlgoliaRuntimeException {
    return LaunderThrowable.await(updateConfigAsync(indexName, configuration, requestOptions));
  }

  /**
   * Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response updateConfigWithHTTPInfo(
    @Nonnull String indexName,
    @Nonnull Configuration configuration,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    return LaunderThrowable.await(updateConfigWithHTTPInfoAsync(indexName, configuration, requestOptions));
  }

  /**
   * Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public BaseResponse updateConfig(@Nonnull String indexName, @Nonnull Configuration configuration) throws AlgoliaRuntimeException {
    return this.updateConfig(indexName, configuration, null);
  }

  /**
   * Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public Response updateConfigWithHTTPInfo(@Nonnull String indexName, @Nonnull Configuration configuration) throws AlgoliaRuntimeException {
    return this.updateConfigWithHTTPInfo(indexName, configuration, null);
  }

  /**
   * (asynchronously) Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> updateConfigAsync(
    @Nonnull String indexName,
    @Nonnull Configuration configuration,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `updateConfig`.");

    Parameters.requireNonNull(configuration, "Parameter `configuration` is required when calling `updateConfig`.");

    HttpRequest request = HttpRequest.builder()
      .setPath("/1/configs/{indexName}", indexName)
      .setMethod("PUT")
      .setBody(configuration)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<BaseResponse>() {});
  }

  /**
   * (asynchronously) Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> updateConfigWithHTTPInfoAsync(
    @Nonnull String indexName,
    @Nonnull Configuration configuration,
    @Nullable RequestOptions requestOptions
  ) throws AlgoliaRuntimeException {
    Parameters.requireNonNull(indexName, "Parameter `indexName` is required when calling `updateConfig`.");

    Parameters.requireNonNull(configuration, "Parameter `configuration` is required when calling `updateConfig`.");

    HttpRequest request = HttpRequest.builder()
      .setPath("/1/configs/{indexName}", indexName)
      .setMethod("PUT")
      .setBody(configuration)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<BaseResponse> updateConfigAsync(@Nonnull String indexName, @Nonnull Configuration configuration)
    throws AlgoliaRuntimeException {
    return this.updateConfigAsync(indexName, configuration, null);
  }

  /**
   * (asynchronously) Updates a QuerySuggestions configuration.
   *
   * @param indexName Query Suggestions index name. (required)
   * @param configuration (required)
   * @throws AlgoliaRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> updateConfigWithHTTPInfoAsync(@Nonnull String indexName, @Nonnull Configuration configuration)
    throws AlgoliaRuntimeException {
    return this.updateConfigWithHTTPInfoAsync(indexName, configuration, null);
  }
}
