// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.usage;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** IndexUsage */
public class IndexUsage {

  @JsonProperty("statistics")
  private List<StatisticEntry> statistics;

  public IndexUsage setStatistics(List<StatisticEntry> statistics) {
    this.statistics = statistics;
    return this;
  }

  public IndexUsage addStatistics(StatisticEntry statisticsItem) {
    if (this.statistics == null) {
      this.statistics = new ArrayList<>();
    }
    this.statistics.add(statisticsItem);
    return this;
  }

  /** Get statistics */
  @javax.annotation.Nullable
  public List<StatisticEntry> getStatistics() {
    return statistics;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexUsage indexUsage = (IndexUsage) o;
    return Objects.equals(this.statistics, indexUsage.statistics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statistics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexUsage {\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
