// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/** Composition */
@JsonDeserialize(as = Composition.class)
public class Composition implements BatchCompositionAction {

  @JsonProperty("objectID")
  private String objectID;

  @JsonProperty("name")
  private String name;

  @JsonProperty("description")
  private String description;

  @JsonProperty("behavior")
  private CompositionBehavior behavior;

  @JsonProperty("sortingStrategy")
  private Map<String, String> sortingStrategy;

  public Composition setObjectID(String objectID) {
    this.objectID = objectID;
    return this;
  }

  /** Composition unique identifier. */
  @javax.annotation.Nonnull
  public String getObjectID() {
    return objectID;
  }

  public Composition setName(String name) {
    this.name = name;
    return this;
  }

  /** Composition name. */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public Composition setDescription(String description) {
    this.description = description;
    return this;
  }

  /** Composition description. */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public Composition setBehavior(CompositionBehavior behavior) {
    this.behavior = behavior;
    return this;
  }

  /** Get behavior */
  @javax.annotation.Nonnull
  public CompositionBehavior getBehavior() {
    return behavior;
  }

  public Composition setSortingStrategy(Map<String, String> sortingStrategy) {
    this.sortingStrategy = sortingStrategy;
    return this;
  }

  public Composition putSortingStrategy(String key, String sortingStrategyItem) {
    if (this.sortingStrategy == null) {
      this.sortingStrategy = new HashMap<>();
    }
    this.sortingStrategy.put(key, sortingStrategyItem);
    return this;
  }

  /**
   * A mapping of sorting labels to the indices (or replicas) that implement those sorting rules.
   * The sorting indices MUST be related to the associated main targeted index in the composition.
   * Each key is the label your frontend sends at runtime (for example, \"Price (asc)\"), and each
   * value is the name of the index that should be queried when that label is selected. When a
   * request includes a \"sortBy\" parameter, the platform looks up the corresponding index in this
   * mapping and uses it to execute the query. The main targeted index is replaced with the sorting
   * strategy index it is mapped to. Up to 20 sorting strategies can be defined.
   */
  @javax.annotation.Nullable
  public Map<String, String> getSortingStrategy() {
    return sortingStrategy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Composition composition = (Composition) o;
    return (
      Objects.equals(this.objectID, composition.objectID) &&
      Objects.equals(this.name, composition.name) &&
      Objects.equals(this.description, composition.description) &&
      Objects.equals(this.behavior, composition.behavior) &&
      Objects.equals(this.sortingStrategy, composition.sortingStrategy)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectID, name, description, behavior, sortingStrategy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Composition {\n");
    sb.append("    objectID: ").append(toIndentedString(objectID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    behavior: ").append(toIndentedString(behavior)).append("\n");
    sb.append("    sortingStrategy: ").append(toIndentedString(sortingStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
