// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** An object containing an `injection` behavior. */
@JsonDeserialize(as = CompositionInjectionBehavior.class)
public class CompositionInjectionBehavior implements CompositionBehavior {

  @JsonProperty("injection")
  private Injection injection;

  public CompositionInjectionBehavior setInjection(Injection injection) {
    this.injection = injection;
    return this;
  }

  /** Get injection */
  @javax.annotation.Nonnull
  public Injection getInjection() {
    return injection;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompositionInjectionBehavior compositionInjectionBehavior = (CompositionInjectionBehavior) o;
    return Objects.equals(this.injection, compositionInjectionBehavior.injection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(injection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompositionInjectionBehavior {\n");
    sb.append("    injection: ").append(toIndentedString(injection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
