// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** External */
public class External {

  @JsonProperty("index")
  private String index;

  @JsonProperty("params")
  private BaseInjectionQueryParameters params;

  @JsonProperty("ordering")
  private ExternalOrdering ordering;

  public External setIndex(String index) {
    this.index = index;
    return this;
  }

  /** Composition Index name. */
  @javax.annotation.Nonnull
  public String getIndex() {
    return index;
  }

  public External setParams(BaseInjectionQueryParameters params) {
    this.params = params;
    return this;
  }

  /** Get params */
  @javax.annotation.Nullable
  public BaseInjectionQueryParameters getParams() {
    return params;
  }

  public External setOrdering(ExternalOrdering ordering) {
    this.ordering = ordering;
    return this;
  }

  /** Get ordering */
  @javax.annotation.Nullable
  public ExternalOrdering getOrdering() {
    return ordering;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    External external = (External) o;
    return (
      Objects.equals(this.index, external.index) &&
      Objects.equals(this.params, external.params) &&
      Objects.equals(this.ordering, external.ordering)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, params, ordering);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class External {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    ordering: ").append(toIndentedString(ordering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
