// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** Recommend */
public class Recommend {

  @JsonProperty("indexName")
  private String indexName;

  @JsonProperty("model")
  private Model model;

  @JsonProperty("threshold")
  private Integer threshold;

  @JsonProperty("queryParameters")
  private BaseInjectionQueryParameters queryParameters;

  @JsonProperty("fallbackParameters")
  private BaseInjectionQueryParameters fallbackParameters;

  public Recommend setIndexName(String indexName) {
    this.indexName = indexName;
    return this;
  }

  /** Index to retrieve recommendations from. */
  @javax.annotation.Nonnull
  public String getIndexName() {
    return indexName;
  }

  public Recommend setModel(Model model) {
    this.model = model;
    return this;
  }

  /** Get model */
  @javax.annotation.Nonnull
  public Model getModel() {
    return model;
  }

  public Recommend setThreshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

  /** Minimum score a recommendation must have to be included. minimum: 0 maximum: 100 */
  @javax.annotation.Nonnull
  public Integer getThreshold() {
    return threshold;
  }

  public Recommend setQueryParameters(BaseInjectionQueryParameters queryParameters) {
    this.queryParameters = queryParameters;
    return this;
  }

  /** Get queryParameters */
  @javax.annotation.Nullable
  public BaseInjectionQueryParameters getQueryParameters() {
    return queryParameters;
  }

  public Recommend setFallbackParameters(BaseInjectionQueryParameters fallbackParameters) {
    this.fallbackParameters = fallbackParameters;
    return this;
  }

  /** Get fallbackParameters */
  @javax.annotation.Nullable
  public BaseInjectionQueryParameters getFallbackParameters() {
    return fallbackParameters;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recommend recommend = (Recommend) o;
    return (
      Objects.equals(this.indexName, recommend.indexName) &&
      Objects.equals(this.model, recommend.model) &&
      Objects.equals(this.threshold, recommend.threshold) &&
      Objects.equals(this.queryParameters, recommend.queryParameters) &&
      Objects.equals(this.fallbackParameters, recommend.fallbackParameters)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(indexName, model, threshold, queryParameters, fallbackParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recommend {\n");
    sb.append("    indexName: ").append(toIndentedString(indexName)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    queryParameters: ").append(toIndentedString(queryParameters)).append("\n");
    sb.append("    fallbackParameters: ").append(toIndentedString(fallbackParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
