// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** ResultsInjectedItemInfoResponse */
public class ResultsInjectedItemInfoResponse {

  @JsonProperty("key")
  private String key;

  @JsonProperty("appliedRules")
  private List<ResultsInjectedItemAppliedRulesInfoResponse> appliedRules;

  private Map<String, Object> additionalProperties = new HashMap<>();

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  @JsonAnySetter
  public ResultsInjectedItemInfoResponse setAdditionalProperty(String name, Object value) {
    this.additionalProperties.put(name, value);
    return this;
  }

  public ResultsInjectedItemInfoResponse setKey(String key) {
    this.key = key;
    return this;
  }

  /** Get key */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public ResultsInjectedItemInfoResponse setAppliedRules(List<ResultsInjectedItemAppliedRulesInfoResponse> appliedRules) {
    this.appliedRules = appliedRules;
    return this;
  }

  public ResultsInjectedItemInfoResponse addAppliedRules(ResultsInjectedItemAppliedRulesInfoResponse appliedRulesItem) {
    if (this.appliedRules == null) {
      this.appliedRules = new ArrayList<>();
    }
    this.appliedRules.add(appliedRulesItem);
    return this;
  }

  /** Get appliedRules */
  @javax.annotation.Nullable
  public List<ResultsInjectedItemAppliedRulesInfoResponse> getAppliedRules() {
    return appliedRules;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsInjectedItemInfoResponse resultsInjectedItemInfoResponse = (ResultsInjectedItemInfoResponse) o;
    return (
      Objects.equals(this.key, resultsInjectedItemInfoResponse.key) &&
      Objects.equals(this.appliedRules, resultsInjectedItemInfoResponse.appliedRules) &&
      super.equals(o)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, appliedRules, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsInjectedItemInfoResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    appliedRules: ").append(toIndentedString(appliedRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
