// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** Composition Rules search parameters. */
public class SearchCompositionRulesParams {

  @JsonProperty("query")
  private String query;

  @JsonProperty("anchoring")
  private Anchoring anchoring;

  @JsonProperty("context")
  private String context;

  @JsonProperty("page")
  private Integer page;

  @JsonProperty("hitsPerPage")
  private Integer hitsPerPage;

  @JsonProperty("enabled")
  private Boolean enabled;

  public SearchCompositionRulesParams setQuery(String query) {
    this.query = query;
    return this;
  }

  /** Search query for rules. */
  @javax.annotation.Nullable
  public String getQuery() {
    return query;
  }

  public SearchCompositionRulesParams setAnchoring(Anchoring anchoring) {
    this.anchoring = anchoring;
    return this;
  }

  /** Get anchoring */
  @javax.annotation.Nullable
  public Anchoring getAnchoring() {
    return anchoring;
  }

  public SearchCompositionRulesParams setContext(String context) {
    this.context = context;
    return this;
  }

  /** Only return composition rules that match the context (exact match). */
  @javax.annotation.Nullable
  public String getContext() {
    return context;
  }

  public SearchCompositionRulesParams setPage(Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Requested page of the API response. Algolia uses `page` and `hitsPerPage` to control how search
   * results are displayed
   * ([paginated](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/)).
   * - `hitsPerPage`: sets the number of search results (_hits_) displayed per page. - `page`:
   * specifies the page number of the search results you want to retrieve. Page numbering starts at
   * 0, so the first page is `page=0`, the second is `page=1`, and so on. For example, to display 10
   * results per page starting from the third page, set `hitsPerPage` to 10 and `page` to 2.
   * minimum: 0
   */
  @javax.annotation.Nullable
  public Integer getPage() {
    return page;
  }

  public SearchCompositionRulesParams setHitsPerPage(Integer hitsPerPage) {
    this.hitsPerPage = hitsPerPage;
    return this;
  }

  /**
   * Maximum number of hits per page. Algolia uses `page` and `hitsPerPage` to control how search
   * results are displayed
   * ([paginated](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/)).
   * - `hitsPerPage`: sets the number of search results (_hits_) displayed per page. - `page`:
   * specifies the page number of the search results you want to retrieve. Page numbering starts at
   * 0, so the first page is `page=0`, the second is `page=1`, and so on. For example, to display 10
   * results per page starting from the third page, set `hitsPerPage` to 10 and `page` to 2.
   * minimum: 1 maximum: 1000
   */
  @javax.annotation.Nullable
  public Integer getHitsPerPage() {
    return hitsPerPage;
  }

  public SearchCompositionRulesParams setEnabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * If `true`, return only enabled composition rules. If `false`, return only inactive composition
   * rules. By default, _all_ composition rules are returned.
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCompositionRulesParams searchCompositionRulesParams = (SearchCompositionRulesParams) o;
    return (
      Objects.equals(this.query, searchCompositionRulesParams.query) &&
      Objects.equals(this.anchoring, searchCompositionRulesParams.anchoring) &&
      Objects.equals(this.context, searchCompositionRulesParams.context) &&
      Objects.equals(this.page, searchCompositionRulesParams.page) &&
      Objects.equals(this.hitsPerPage, searchCompositionRulesParams.hitsPerPage) &&
      Objects.equals(this.enabled, searchCompositionRulesParams.enabled)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, anchoring, context, page, hitsPerPage, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCompositionRulesParams {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    anchoring: ").append(toIndentedString(anchoring)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    hitsPerPage: ").append(toIndentedString(hitsPerPage)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
