// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/** A response to an interrupt emitted by a preceding AG-UI run. */
public class AguiResume {

  @JsonProperty("interruptId")
  private String interruptId;

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("payload")
  private Map<String, Object> payload;

  public AguiResume setInterruptId(String interruptId) {
    this.interruptId = interruptId;
    return this;
  }

  /** Get interruptId */
  @javax.annotation.Nonnull
  public String getInterruptId() {
    return interruptId;
  }

  public AguiResume setStatus(StatusEnum status) {
    this.status = status;
    return this;
  }

  /** Get status */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public AguiResume setPayload(Map<String, Object> payload) {
    this.payload = payload;
    return this;
  }

  public AguiResume putPayload(String key, Object payloadItem) {
    if (this.payload == null) {
      this.payload = new HashMap<>();
    }
    this.payload.put(key, payloadItem);
    return this;
  }

  /** Get payload */
  @javax.annotation.Nullable
  public Map<String, Object> getPayload() {
    return payload;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AguiResume aguiResume = (AguiResume) o;
    return (
      Objects.equals(this.interruptId, aguiResume.interruptId) &&
      Objects.equals(this.status, aguiResume.status) &&
      Objects.equals(this.payload, aguiResume.payload)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(interruptId, status, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AguiResume {\n");
    sb.append("    interruptId: ").append(toIndentedString(interruptId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
