// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** Single allowed domain in API responses. */
public class AllowedDomainResponse {

  @JsonProperty("id")
  private String id;

  @JsonProperty("appId")
  private String appId;

  @JsonProperty("agentId")
  private String agentId;

  @JsonProperty("domain")
  private String domain;

  @JsonProperty("createdAt")
  private String createdAt;

  @JsonProperty("updatedAt")
  private String updatedAt;

  public AllowedDomainResponse setId(String id) {
    this.id = id;
    return this;
  }

  /** Get id */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public AllowedDomainResponse setAppId(String appId) {
    this.appId = appId;
    return this;
  }

  /** Get appId */
  @javax.annotation.Nonnull
  public String getAppId() {
    return appId;
  }

  public AllowedDomainResponse setAgentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

  /** Get agentId */
  @javax.annotation.Nonnull
  public String getAgentId() {
    return agentId;
  }

  public AllowedDomainResponse setDomain(String domain) {
    this.domain = domain;
    return this;
  }

  /** Get domain */
  @javax.annotation.Nonnull
  public String getDomain() {
    return domain;
  }

  public AllowedDomainResponse setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /** Get createdAt */
  @javax.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public AllowedDomainResponse setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /** Get updatedAt */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllowedDomainResponse allowedDomainResponse = (AllowedDomainResponse) o;
    return (
      Objects.equals(this.id, allowedDomainResponse.id) &&
      Objects.equals(this.appId, allowedDomainResponse.appId) &&
      Objects.equals(this.agentId, allowedDomainResponse.agentId) &&
      Objects.equals(this.domain, allowedDomainResponse.domain) &&
      Objects.equals(this.createdAt, allowedDomainResponse.createdAt) &&
      Objects.equals(this.updatedAt, allowedDomainResponse.updatedAt)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, appId, agentId, domain, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllowedDomainResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
