// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/**
 * Before/after accounting for a context operation. ``tokens*Estimate`` fields are heuristic, not an
 * authoritative provider count. ``messages_dropped`` is the net reduction in message count
 * (``messages_before - messages_after``); for compaction the summarized tail is replaced by a
 * single summary message, so this reflects the net change rather than a raw delete count.
 */
public class ContextStats {

  @JsonProperty("messagesBefore")
  private Integer messagesBefore;

  @JsonProperty("messagesAfter")
  private Integer messagesAfter;

  @JsonProperty("tokensBeforeEstimate")
  private Integer tokensBeforeEstimate;

  @JsonProperty("tokensAfterEstimate")
  private Integer tokensAfterEstimate;

  @JsonProperty("messagesDropped")
  private Integer messagesDropped;

  public ContextStats setMessagesBefore(Integer messagesBefore) {
    this.messagesBefore = messagesBefore;
    return this;
  }

  /** Message count before the operation. */
  @javax.annotation.Nonnull
  public Integer getMessagesBefore() {
    return messagesBefore;
  }

  public ContextStats setMessagesAfter(Integer messagesAfter) {
    this.messagesAfter = messagesAfter;
    return this;
  }

  /** Message count after the operation. */
  @javax.annotation.Nonnull
  public Integer getMessagesAfter() {
    return messagesAfter;
  }

  public ContextStats setTokensBeforeEstimate(Integer tokensBeforeEstimate) {
    this.tokensBeforeEstimate = tokensBeforeEstimate;
    return this;
  }

  /** Estimated token count before the operation. */
  @javax.annotation.Nonnull
  public Integer getTokensBeforeEstimate() {
    return tokensBeforeEstimate;
  }

  public ContextStats setTokensAfterEstimate(Integer tokensAfterEstimate) {
    this.tokensAfterEstimate = tokensAfterEstimate;
    return this;
  }

  /** Estimated token count after the operation. */
  @javax.annotation.Nonnull
  public Integer getTokensAfterEstimate() {
    return tokensAfterEstimate;
  }

  public ContextStats setMessagesDropped(Integer messagesDropped) {
    this.messagesDropped = messagesDropped;
    return this;
  }

  /** Net reduction in message count (before - after). */
  @javax.annotation.Nonnull
  public Integer getMessagesDropped() {
    return messagesDropped;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextStats contextStats = (ContextStats) o;
    return (
      Objects.equals(this.messagesBefore, contextStats.messagesBefore) &&
      Objects.equals(this.messagesAfter, contextStats.messagesAfter) &&
      Objects.equals(this.tokensBeforeEstimate, contextStats.tokensBeforeEstimate) &&
      Objects.equals(this.tokensAfterEstimate, contextStats.tokensAfterEstimate) &&
      Objects.equals(this.messagesDropped, contextStats.messagesDropped)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(messagesBefore, messagesAfter, tokensBeforeEstimate, tokensAfterEstimate, messagesDropped);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextStats {\n");
    sb.append("    messagesBefore: ").append(toIndentedString(messagesBefore)).append("\n");
    sb.append("    messagesAfter: ").append(toIndentedString(messagesAfter)).append("\n");
    sb.append("    tokensBeforeEstimate: ").append(toIndentedString(tokensBeforeEstimate)).append("\n");
    sb.append("    tokensAfterEstimate: ").append(toIndentedString(tokensAfterEstimate)).append("\n");
    sb.append("    messagesDropped: ").append(toIndentedString(messagesDropped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
