// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/**
 * Views, clicks, and conversions attributed to the conversation. Returned only when
 * ``includeImpactAnalytics=true``. ``null`` means the API could not supply the data -- NOT that
 * there are zero outcomes -- and the response sets ``analyticsDegraded`` to ``true``. Render that
 * case as a data-load error rather than as zero-value badges.
 */
public class ImpactAnalytics {

  @JsonProperty("hasView")
  private Boolean hasView;

  @JsonProperty("hasClick")
  private Boolean hasClick;

  @JsonProperty("hasConversion")
  private Boolean hasConversion;

  @JsonProperty("hasAlgoliaSearch")
  private Boolean hasAlgoliaSearch;

  public ImpactAnalytics setHasView(Boolean hasView) {
    this.hasView = hasView;
    return this;
  }

  /** Get hasView */
  @javax.annotation.Nonnull
  public Boolean getHasView() {
    return hasView;
  }

  public ImpactAnalytics setHasClick(Boolean hasClick) {
    this.hasClick = hasClick;
    return this;
  }

  /** Get hasClick */
  @javax.annotation.Nonnull
  public Boolean getHasClick() {
    return hasClick;
  }

  public ImpactAnalytics setHasConversion(Boolean hasConversion) {
    this.hasConversion = hasConversion;
    return this;
  }

  /** Get hasConversion */
  @javax.annotation.Nonnull
  public Boolean getHasConversion() {
    return hasConversion;
  }

  public ImpactAnalytics setHasAlgoliaSearch(Boolean hasAlgoliaSearch) {
    this.hasAlgoliaSearch = hasAlgoliaSearch;
    return this;
  }

  /** Get hasAlgoliaSearch */
  @javax.annotation.Nonnull
  public Boolean getHasAlgoliaSearch() {
    return hasAlgoliaSearch;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImpactAnalytics impactAnalytics = (ImpactAnalytics) o;
    return (
      Objects.equals(this.hasView, impactAnalytics.hasView) &&
      Objects.equals(this.hasClick, impactAnalytics.hasClick) &&
      Objects.equals(this.hasConversion, impactAnalytics.hasConversion) &&
      Objects.equals(this.hasAlgoliaSearch, impactAnalytics.hasAlgoliaSearch)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasView, hasClick, hasConversion, hasAlgoliaSearch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImpactAnalytics {\n");
    sb.append("    hasView: ").append(toIndentedString(hasView)).append("\n");
    sb.append("    hasClick: ").append(toIndentedString(hasClick)).append("\n");
    sb.append("    hasConversion: ").append(toIndentedString(hasConversion)).append("\n");
    sb.append("    hasAlgoliaSearch: ").append(toIndentedString(hasAlgoliaSearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
