// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.algolia.exceptions.AlgoliaRuntimeException;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;
import java.util.logging.Logger;

/** MessagePartAssistantMessageAGUI */
@JsonDeserialize(using = MessagePartAssistantMessageAGUI.Deserializer.class)
public interface MessagePartAssistantMessageAGUI {
  class Deserializer extends JsonDeserializer<MessagePartAssistantMessageAGUI> {

    private static final Logger LOGGER = Logger.getLogger(Deserializer.class.getName());

    @Override
    public MessagePartAssistantMessageAGUI deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
      JsonNode tree = jp.readValueAsTree();
      JsonNode discriminatorNode = tree.get("type");
      if (discriminatorNode != null && discriminatorNode.isTextual()) {
        String discriminatorValue = discriminatorNode.asText();
        if ("text".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(TextPartAGUI.class);
          }
        }
        if ("thinking".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ReasoningPartAGUI.class);
          }
        }
        if ("tool-call".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ToolCallPartAGUI.class);
          }
        }
        if ("tool-result".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ToolCallResultPartAGUI.class);
          }
        }
      }
      // deserialize ToolCallPartAGUI
      if (tree.isObject() && tree.has("arguments") && tree.has("id") && tree.has("name")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ToolCallPartAGUI.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ToolCallPartAGUI (error: " + e.getMessage() + ") (type: ToolCallPartAGUI)");
        }
      }
      // deserialize ToolCallResultPartAGUI
      if (tree.isObject() && tree.has("toolCallId")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ToolCallResultPartAGUI.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf ToolCallResultPartAGUI (error: " + e.getMessage() + ") (type: ToolCallResultPartAGUI)"
          );
        }
      }
      // deserialize TextPartAGUI
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(TextPartAGUI.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf TextPartAGUI (error: " + e.getMessage() + ") (type: TextPartAGUI)");
        }
      }
      // deserialize ReasoningPartAGUI
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ReasoningPartAGUI.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ReasoningPartAGUI (error: " + e.getMessage() + ") (type: ReasoningPartAGUI)");
        }
      }
      throw new AlgoliaRuntimeException(String.format("Failed to deserialize json element: %s", tree));
    }

    /** Handle deserialization of the 'null' value. */
    @Override
    public MessagePartAssistantMessageAGUI getNullValue(DeserializationContext ctxt) throws JsonMappingException {
      throw new JsonMappingException(ctxt.getParser(), "MessagePartAssistantMessageAGUI cannot be null");
    }
  }
}
