// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.algolia.exceptions.AlgoliaRuntimeException;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;
import java.util.logging.Logger;

/** MessagePart */
@JsonDeserialize(using = MessagePart.Deserializer.class)
public interface MessagePart {
  class Deserializer extends JsonDeserializer<MessagePart> {

    private static final Logger LOGGER = Logger.getLogger(Deserializer.class.getName());

    @Override
    public MessagePart deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
      JsonNode tree = jp.readValueAsTree();
      JsonNode discriminatorNode = tree.get("type");
      if (discriminatorNode != null && discriminatorNode.isTextual()) {
        String discriminatorValue = discriminatorNode.asText();
        if ("reasoning".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ReasoningPart.class);
          }
        }
        if ("start".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(StartPart.class);
          }
        }
        if ("start-step".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(StartStepPart.class);
          }
        }
        if ("text".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(TextPart.class);
          }
        }
        if ("tool-approval-request".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ToolApprovalRequestPart.class);
          }
        }
        if ("tool-call".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ToolCallPart.class);
          }
        }
        if ("tool-result".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ToolResultPart.class);
          }
        }
      }
      // deserialize ToolResultPart
      if (tree.isObject() && tree.has("output")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ToolResultPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ToolResultPart (error: " + e.getMessage() + ") (type: ToolResultPart)");
        }
      }
      // deserialize TextPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(TextPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf TextPart (error: " + e.getMessage() + ") (type: TextPart)");
        }
      }
      // deserialize ToolCallPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ToolCallPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ToolCallPart (error: " + e.getMessage() + ") (type: ToolCallPart)");
        }
      }
      // deserialize StartPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(StartPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf StartPart (error: " + e.getMessage() + ") (type: StartPart)");
        }
      }
      // deserialize StartStepPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(StartStepPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf StartStepPart (error: " + e.getMessage() + ") (type: StartStepPart)");
        }
      }
      // deserialize ReasoningPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ReasoningPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ReasoningPart (error: " + e.getMessage() + ") (type: ReasoningPart)");
        }
      }
      // deserialize ToolApprovalRequestPart
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ToolApprovalRequestPart.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf ToolApprovalRequestPart (error: " + e.getMessage() + ") (type: ToolApprovalRequestPart)"
          );
        }
      }
      throw new AlgoliaRuntimeException(String.format("Failed to deserialize json element: %s", tree));
    }

    /** Handle deserialization of the 'null' value. */
    @Override
    public MessagePart getNullValue(DeserializationContext ctxt) throws JsonMappingException {
      throw new JsonMappingException(ctxt.getParser(), "MessagePart cannot be null");
    }
  }
}
