// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** OpenAI-specific provider input. */
@JsonDeserialize(as = OpenAIProviderInput.class)
public class OpenAIProviderInput implements ProviderInputNullable, ProviderInput {

  @JsonProperty("apiKey")
  private String apiKey;

  @JsonProperty("baseUrl")
  private String baseUrl;

  public OpenAIProviderInput setApiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

  /** Get apiKey */
  @javax.annotation.Nonnull
  public String getApiKey() {
    return apiKey;
  }

  public OpenAIProviderInput setBaseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

  /** Get baseUrl */
  @javax.annotation.Nullable
  public String getBaseUrl() {
    return baseUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenAIProviderInput openAIProviderInput = (OpenAIProviderInput) o;
    return Objects.equals(this.apiKey, openAIProviderInput.apiKey) && Objects.equals(this.baseUrl, openAIProviderInput.baseUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, baseUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenAIProviderInput {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
