// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.algolia.exceptions.AlgoliaRuntimeException;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;
import java.util.logging.Logger;

/** ProviderInput */
@JsonDeserialize(using = ProviderInput.Deserializer.class)
public interface ProviderInput {
  class Deserializer extends JsonDeserializer<ProviderInput> {

    private static final Logger LOGGER = Logger.getLogger(Deserializer.class.getName());

    @Override
    public ProviderInput deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
      JsonNode tree = jp.readValueAsTree();
      // deserialize AzureOpenAIProviderInput
      if (tree.isObject() && tree.has("azureDeployment") && tree.has("azureEndpoint")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AzureOpenAIProviderInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AzureOpenAIProviderInput (error: " + e.getMessage() + ") (type: AzureOpenAIProviderInput)"
          );
        }
      }
      // deserialize OpenAICompatibleProviderInput
      if (tree.isObject() && tree.has("baseUrl") && tree.has("defaultModel")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(OpenAICompatibleProviderInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf OpenAICompatibleProviderInput (error: " +
              e.getMessage() +
              ") (type: OpenAICompatibleProviderInput)"
          );
        }
      }
      // deserialize OpenAIProviderInput
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(OpenAIProviderInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf OpenAIProviderInput (error: " + e.getMessage() + ") (type: OpenAIProviderInput)");
        }
      }
      // deserialize BaseProviderInput
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(BaseProviderInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf BaseProviderInput (error: " + e.getMessage() + ") (type: BaseProviderInput)");
        }
      }
      // deserialize AnthropicProviderInput
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AnthropicProviderInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AnthropicProviderInput (error: " + e.getMessage() + ") (type: AnthropicProviderInput)"
          );
        }
      }
      throw new AlgoliaRuntimeException(String.format("Failed to deserialize json element: %s", tree));
    }

    /** Handle deserialization of the 'null' value. */
    @Override
    public ProviderInput getNullValue(DeserializationContext ctxt) throws JsonMappingException {
      throw new JsonMappingException(ctxt.getParser(), "ProviderInput cannot be null");
    }
  }
}
