// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Algolia Search API parameters that can be predefined for the search tool. Reference:
 * https://www.algolia.com/doc/api-reference/search-api-parameters/ A subset of SearchParameters of
 * specific params we allow for runtime override.
 */
public class SearchParametersOverrides {

  @JsonProperty("filters")
  private String filters;

  @JsonProperty("attributesToRetrieve")
  private List<String> attributesToRetrieve;

  @JsonProperty("restrictSearchableAttributes")
  private List<String> restrictSearchableAttributes;

  @JsonProperty("distinct")
  private DistinctUnion distinct;

  @JsonProperty("userToken")
  private String userToken;

  @JsonProperty("enablePersonalization")
  private Boolean enablePersonalization;

  @JsonProperty("personalizationImpact")
  private Integer personalizationImpact;

  @JsonProperty("optionalFilters")
  private OptionalFiltersUnion optionalFilters;

  public SearchParametersOverrides setFilters(String filters) {
    this.filters = filters;
    return this;
  }

  /** Get filters */
  @javax.annotation.Nullable
  public String getFilters() {
    return filters;
  }

  public SearchParametersOverrides setAttributesToRetrieve(List<String> attributesToRetrieve) {
    this.attributesToRetrieve = attributesToRetrieve;
    return this;
  }

  public SearchParametersOverrides addAttributesToRetrieve(String attributesToRetrieveItem) {
    if (this.attributesToRetrieve == null) {
      this.attributesToRetrieve = new ArrayList<>();
    }
    this.attributesToRetrieve.add(attributesToRetrieveItem);
    return this;
  }

  /** Get attributesToRetrieve */
  @javax.annotation.Nullable
  public List<String> getAttributesToRetrieve() {
    return attributesToRetrieve;
  }

  public SearchParametersOverrides setRestrictSearchableAttributes(List<String> restrictSearchableAttributes) {
    this.restrictSearchableAttributes = restrictSearchableAttributes;
    return this;
  }

  public SearchParametersOverrides addRestrictSearchableAttributes(String restrictSearchableAttributesItem) {
    if (this.restrictSearchableAttributes == null) {
      this.restrictSearchableAttributes = new ArrayList<>();
    }
    this.restrictSearchableAttributes.add(restrictSearchableAttributesItem);
    return this;
  }

  /** Get restrictSearchableAttributes */
  @javax.annotation.Nullable
  public List<String> getRestrictSearchableAttributes() {
    return restrictSearchableAttributes;
  }

  public SearchParametersOverrides setDistinct(DistinctUnion distinct) {
    this.distinct = distinct;
    return this;
  }

  /** Get distinct */
  @javax.annotation.Nullable
  public DistinctUnion getDistinct() {
    return distinct;
  }

  public SearchParametersOverrides setUserToken(String userToken) {
    this.userToken = userToken;
    return this;
  }

  /** Get userToken */
  @javax.annotation.Nullable
  public String getUserToken() {
    return userToken;
  }

  public SearchParametersOverrides setEnablePersonalization(Boolean enablePersonalization) {
    this.enablePersonalization = enablePersonalization;
    return this;
  }

  /** Get enablePersonalization */
  @javax.annotation.Nullable
  public Boolean getEnablePersonalization() {
    return enablePersonalization;
  }

  public SearchParametersOverrides setPersonalizationImpact(Integer personalizationImpact) {
    this.personalizationImpact = personalizationImpact;
    return this;
  }

  /** Get personalizationImpact */
  @javax.annotation.Nullable
  public Integer getPersonalizationImpact() {
    return personalizationImpact;
  }

  public SearchParametersOverrides setOptionalFilters(OptionalFiltersUnion optionalFilters) {
    this.optionalFilters = optionalFilters;
    return this;
  }

  /** Get optionalFilters */
  @javax.annotation.Nullable
  public OptionalFiltersUnion getOptionalFilters() {
    return optionalFilters;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchParametersOverrides searchParametersOverrides = (SearchParametersOverrides) o;
    return (
      Objects.equals(this.filters, searchParametersOverrides.filters) &&
      Objects.equals(this.attributesToRetrieve, searchParametersOverrides.attributesToRetrieve) &&
      Objects.equals(this.restrictSearchableAttributes, searchParametersOverrides.restrictSearchableAttributes) &&
      Objects.equals(this.distinct, searchParametersOverrides.distinct) &&
      Objects.equals(this.userToken, searchParametersOverrides.userToken) &&
      Objects.equals(this.enablePersonalization, searchParametersOverrides.enablePersonalization) &&
      Objects.equals(this.personalizationImpact, searchParametersOverrides.personalizationImpact) &&
      Objects.equals(this.optionalFilters, searchParametersOverrides.optionalFilters)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(
      filters,
      attributesToRetrieve,
      restrictSearchableAttributes,
      distinct,
      userToken,
      enablePersonalization,
      personalizationImpact,
      optionalFilters
    );
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchParametersOverrides {\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    attributesToRetrieve: ").append(toIndentedString(attributesToRetrieve)).append("\n");
    sb.append("    restrictSearchableAttributes: ").append(toIndentedString(restrictSearchableAttributes)).append("\n");
    sb.append("    distinct: ").append(toIndentedString(distinct)).append("\n");
    sb.append("    userToken: ").append(toIndentedString(userToken)).append("\n");
    sb.append("    enablePersonalization: ").append(toIndentedString(enablePersonalization)).append("\n");
    sb.append("    personalizationImpact: ").append(toIndentedString(personalizationImpact)).append("\n");
    sb.append("    optionalFilters: ").append(toIndentedString(optionalFilters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
