// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Secret key creation payload. */
public class SecretKeyCreate {

  @JsonProperty("name")
  private String name;

  @JsonProperty("agentIds")
  private List<String> agentIds;

  public SecretKeyCreate setName(String name) {
    this.name = name;
    return this;
  }

  /** The name of the secret key. */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public SecretKeyCreate setAgentIds(List<String> agentIds) {
    this.agentIds = agentIds;
    return this;
  }

  public SecretKeyCreate addAgentIds(String agentIdsItem) {
    if (this.agentIds == null) {
      this.agentIds = new ArrayList<>();
    }
    this.agentIds.add(agentIdsItem);
    return this;
  }

  /** List of agent IDs this secret key is associated with. */
  @javax.annotation.Nullable
  public List<String> getAgentIds() {
    return agentIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretKeyCreate secretKeyCreate = (SecretKeyCreate) o;
    return Objects.equals(this.name, secretKeyCreate.name) && Objects.equals(this.agentIds, secretKeyCreate.agentIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, agentIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretKeyCreate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    agentIds: ").append(toIndentedString(agentIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
