// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.algolia.exceptions.AlgoliaRuntimeException;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;
import java.util.logging.Logger;

/** ToolConfigInput */
@JsonDeserialize(using = ToolConfigInput.Deserializer.class)
public interface ToolConfigInput {
  // ToolConfigInput as UnknownToolConfig wrapper.
  static ToolConfigInput of(UnknownToolConfig value) {
    return new UnknownToolConfigWrapper(value);
  }

  // ToolConfigInput as UnknownToolConfig wrapper.
  @JsonSerialize(using = UnknownToolConfigWrapper.Serializer.class)
  class UnknownToolConfigWrapper implements ToolConfigInput {

    private final UnknownToolConfig value;

    UnknownToolConfigWrapper(UnknownToolConfig value) {
      this.value = value;
    }

    public UnknownToolConfig getValue() {
      return value;
    }

    static class Serializer extends JsonSerializer<UnknownToolConfigWrapper> {

      @Override
      public void serialize(UnknownToolConfigWrapper value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        gen.writeObject(value.getValue());
      }
    }
  }

  class Deserializer extends JsonDeserializer<ToolConfigInput> {

    private static final Logger LOGGER = Logger.getLogger(Deserializer.class.getName());

    @Override
    public ToolConfigInput deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
      JsonNode tree = jp.readValueAsTree();
      JsonNode discriminatorNode = tree.get("type");
      if (discriminatorNode != null && discriminatorNode.isTextual()) {
        String discriminatorValue = discriminatorNode.asText();
        if ("algolia_display_results".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(AlgoliaDisplayResultsToolConfig.class);
          }
        }
        if ("algolia_recommend".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(AlgoliaRecommendToolConfigInput.class);
          }
        }
        if ("algolia_search_index".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(AlgoliaSearchToolConfig.class);
          }
        }
        if ("client_side".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(ClientSideToolConfig.class);
          }
        }
        if ("mcp_tools".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(McpServerToolConfig.class);
          }
        }
        if ("unknown".equals(discriminatorValue)) {
          try (JsonParser parser = tree.traverse(jp.getCodec())) {
            return parser.readValueAs(UnknownToolConfig.class);
          }
        }
      }
      // deserialize ClientSideToolConfig
      if (tree.isObject() && tree.has("description") && tree.has("inputSchema")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(ClientSideToolConfig.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf ClientSideToolConfig (error: " + e.getMessage() + ") (type: ClientSideToolConfig)");
        }
      }
      // deserialize McpServerToolConfig
      if (tree.isObject() && tree.has("headers") && tree.has("url")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(McpServerToolConfig.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf McpServerToolConfig (error: " + e.getMessage() + ") (type: McpServerToolConfig)");
        }
      }
      // deserialize AlgoliaSearchToolConfig
      if (tree.isObject() && tree.has("indices")) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AlgoliaSearchToolConfig.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AlgoliaSearchToolConfig (error: " + e.getMessage() + ") (type: AlgoliaSearchToolConfig)"
          );
        }
      }
      // deserialize AlgoliaRecommendToolConfigInput
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AlgoliaRecommendToolConfigInput.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AlgoliaRecommendToolConfigInput (error: " +
              e.getMessage() +
              ") (type: AlgoliaRecommendToolConfigInput)"
          );
        }
      }
      // deserialize AlgoliaDisplayResultsToolConfig
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          return parser.readValueAs(AlgoliaDisplayResultsToolConfig.class);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest(
            "Failed to deserialize oneOf AlgoliaDisplayResultsToolConfig (error: " +
              e.getMessage() +
              ") (type: AlgoliaDisplayResultsToolConfig)"
          );
        }
      }
      // deserialize UnknownToolConfig
      if (tree.isObject()) {
        try (JsonParser parser = tree.traverse(jp.getCodec())) {
          UnknownToolConfig value = parser.readValueAs(UnknownToolConfig.class);
          return new ToolConfigInput.UnknownToolConfigWrapper(value);
        } catch (Exception e) {
          // deserialization failed, continue
          LOGGER.finest("Failed to deserialize oneOf UnknownToolConfig (error: " + e.getMessage() + ") (type: UnknownToolConfig)");
        }
      }
      throw new AlgoliaRuntimeException(String.format("Failed to deserialize json element: %s", tree));
    }

    /** Handle deserialization of the 'null' value. */
    @Override
    public ToolConfigInput getNullValue(DeserializationContext ctxt) throws JsonMappingException {
      throw new JsonMappingException(ctxt.getParser(), "ToolConfigInput cannot be null");
    }
  }
}
