// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** UserMessageAGUI */
@JsonDeserialize(as = UserMessageAGUI.class)
public class UserMessageAGUI implements ItemsUnionAguiCompletionRequest {

  @JsonProperty("id")
  private String id;

  @JsonProperty("role")
  private String role;

  @JsonProperty("parts")
  private List<TextPartAGUI> parts;

  @JsonProperty("createdAt")
  private String createdAt;

  @JsonProperty("content")
  private String content;

  @JsonProperty("metadata")
  private UserMessageMetadataAGUI metadata;

  public UserMessageAGUI setId(String id) {
    this.id = id;
    return this;
  }

  /** Get id */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public UserMessageAGUI setRole(String role) {
    this.role = role;
    return this;
  }

  /** Get role */
  @javax.annotation.Nonnull
  public String getRole() {
    return role;
  }

  public UserMessageAGUI setParts(List<TextPartAGUI> parts) {
    this.parts = parts;
    return this;
  }

  public UserMessageAGUI addParts(TextPartAGUI partsItem) {
    if (this.parts == null) {
      this.parts = new ArrayList<>();
    }
    this.parts.add(partsItem);
    return this;
  }

  /** Get parts */
  @javax.annotation.Nullable
  public List<TextPartAGUI> getParts() {
    return parts;
  }

  public UserMessageAGUI setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /** Get createdAt */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public UserMessageAGUI setContent(String content) {
    this.content = content;
    return this;
  }

  /** Get content */
  @javax.annotation.Nonnull
  public String getContent() {
    return content;
  }

  public UserMessageAGUI setMetadata(UserMessageMetadataAGUI metadata) {
    this.metadata = metadata;
    return this;
  }

  /** Get metadata */
  @javax.annotation.Nullable
  public UserMessageMetadataAGUI getMetadata() {
    return metadata;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserMessageAGUI userMessageAGUI = (UserMessageAGUI) o;
    return (
      Objects.equals(this.id, userMessageAGUI.id) &&
      Objects.equals(this.role, userMessageAGUI.role) &&
      Objects.equals(this.parts, userMessageAGUI.parts) &&
      Objects.equals(this.createdAt, userMessageAGUI.createdAt) &&
      Objects.equals(this.content, userMessageAGUI.content) &&
      Objects.equals(this.metadata, userMessageAGUI.metadata)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, role, parts, createdAt, content, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserMessageAGUI {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
