// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** UserDataResponse */
public class UserDataResponse {

  @JsonProperty("conversations")
  private List<ConversationFullResponse> conversations = new ArrayList<>();

  @JsonProperty("memories")
  private List<MemoryRecord> memories = new ArrayList<>();

  public UserDataResponse setConversations(List<ConversationFullResponse> conversations) {
    this.conversations = conversations;
    return this;
  }

  public UserDataResponse addConversations(ConversationFullResponse conversationsItem) {
    this.conversations.add(conversationsItem);
    return this;
  }

  /** Get conversations */
  @javax.annotation.Nonnull
  public List<ConversationFullResponse> getConversations() {
    return conversations;
  }

  public UserDataResponse setMemories(List<MemoryRecord> memories) {
    this.memories = memories;
    return this;
  }

  public UserDataResponse addMemories(MemoryRecord memoriesItem) {
    this.memories.add(memoriesItem);
    return this;
  }

  /** Get memories */
  @javax.annotation.Nonnull
  public List<MemoryRecord> getMemories() {
    return memories;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDataResponse userDataResponse = (UserDataResponse) o;
    return Objects.equals(this.conversations, userDataResponse.conversations) && Objects.equals(this.memories, userDataResponse.memories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversations, memories);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDataResponse {\n");
    sb.append("    conversations: ").append(toIndentedString(conversations)).append("\n");
    sb.append("    memories: ").append(toIndentedString(memories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
