# query
HitsPerPage:
  name: hitsPerPage
  description: Number of users to retrieve per page.
  in: query
  schema:
    type: integer
    description: Number of hits per page.
    default: 20

UserIDInQuery:
  name: X-Algolia-User-ID
  description: userID to assign.
  in: query
  required: true
  schema:
    type: string
    pattern: '^[a-zA-Z0-9 \-*.]+$'

# path
UserIDInPath:
  name: userID
  description: userID to assign.
  in: path
  required: true
  schema:
    type: string
    pattern: '^[a-zA-Z0-9 \-*.]+$'

# misc
userID:
  type: string
  pattern: '^[a-zA-Z0-9 \-*.]+$'
  description: userID of the user.
  example: user1
