name: Checks

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

  specs:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache

      - name: Checking search specs
        run: yarn build:specs search

      - name: Checking recommend specs
        run: yarn build:specs recommend

      - name: Checking personalization specs
        run: yarn build:specs personalization

      - name: Checking analytics specs
        run: yarn build:specs analytics

      - name: Lint
        run: yarn specs:lint

  client_javascript:
    runs-on: ubuntu-20.04
    needs: [setup, specs]
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache

      - name: Generate search client
        run: yarn generate javascript search

      - name: Build search client
        run: yarn build:clients javascript search

      - name: Generate recommend client
        run: yarn generate javascript recommend

      - name: Build recommend client
        run: yarn build:clients javascript recommend

      - name: Generate personalization client
        run: yarn generate javascript personalization

      - name: Build personalization client
        run: yarn build:clients javascript personalization

      - name: Generate analytics client
        run: yarn generate javascript analytics

      - name: Build analytics client
        run: yarn build:clients javascript analytics

      - name: Lint
        run: yarn lint

  client_java:
    runs-on: ubuntu-20.04
    needs: [setup, specs]
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache

      - name: Generate search client
        run: yarn generate java search

      - name: Build search client
        run: yarn build:clients java search

  cts:
    runs-on: ubuntu-20.04
    needs: [setup, specs, client_javascript, client_java]
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache

      - name: Generate clients
        run: yarn generate

      - name: Build client
        run: yarn build:clients

      - name: Generate CTS
        run: yarn cts:generate

      - name: Run CTS
        run: yarn cts:test
